# Assignment #03
1. Explore College Scorecard website - https://collegescorecard.ed.gov/ 

2. Explore College Scorecard Data web page - https://collegescorecard.ed.gov/data/

3. Download and skim the documentation - https://collegescorecard.ed.gov/assets/FullDataDocumentation.pdf

4. Download the dataset - https://ed-public-download.app.cloud.gov/downloads/CollegeScorecard_Raw_Data.zip (265MB Zip File)

5. Unzip the file into a folder (there are many files, one for each school year)

6. Import the 2017-2018 school year file "MERGED2017_18_PP.csv" and explore:   

    * how many colleges or rows?   

    * how many variables or columns?   

    * Look at the first 20 rows   

    * look at the last 20 rows   

    * Look at a random sample of 20 rows    

7. Since there are too many variables to explore, many of which are not interesting. Modify your import statement to only import the following 9 variables:

- UNITID
- INSTNM
- CITY
- STABBR
- ZIP
- ADM_RATE
- UGDS
- TUITIONFEE_IN
- MN_EARN_WNE_P10 

8. Download and read the data dictionary file - https://collegescorecard.ed.gov/assets/CollegeScorecardDataDictionary.xlsx

Find out the definition of the above 9 variables and document the definitions in the Jupyter Notebook so that the readers will not need to repeat what you have done to know the meaning of these variables.

9. Use the predefined cells below to conduct and document your data exploration.

When in doubt, Google. Find examples and read documents/tutorials. 

Have fun!

In [1]:
# Import libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import random
import warnings
warnings.filterwarnings("ignore")

In [2]:
# load the 2017-2018 school year file "MERGED2017_18_PP.csv"   
data=pd.read_csv('CollegeScorecard_Raw_Data/MERGED2017_18_PP.csv')

In [3]:
# Find out how many colleges or rows?   
# Find out how many variables or columns? 
data.shape

(7112, 1977)

Data has 7112 rows and 1977 columns

In [4]:
len(data['INSTNM'].unique())

6978

There are 6978 Unique college names, but they might be from different region
For Example:
University of Maryland, Baltimore County
University of Maryland, Baltimore County (Shady Groove)

In [5]:
# Select all duplicate rows based on one column
# Tried to single out duplicates, but did not work properly. Will look into this again
duplicateRowsDF = data[data.duplicated(['INSTNM', 'CITY','STABBR'])]
len(duplicateRowsDF)
#print("Duplicate Rows based on a single column are:", duplicateRowsDF, sep='\n')

18

In [7]:
duplicateRowsDF.head(3)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMAWDP8_NOTFIRSTTIME_POOLED_SUPP,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP
919,143491,2349500,23495,Cannella School of Hair Design-Chicago,Chicago,IL,60632-2549,National Accrediting Commission of Career Arts...,cannellabeautyschools.com,cannellabeautyschools.com/cbs_disclosures.html,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3439,224679,2098300,20983,Western Technical College,El Paso,TX,79927,Accrediting Commission of Career Schools and C...,www.westerntech.edu,www.westerntech.edu/NetPrice/,...,0.8107,0.1183,0,0.0468,0.7857,0.1676,0,0.0192,0.6782,0.3027
4634,421665,3109700,31097,Cadillac Institute of Cosmetology,Cadillac,MI,49601-1800,NaN,instituteofcos.com,instituteofcos.net/netprice/npcalc.htm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
# Look at the first 20 rows  
data.head(20)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMAWDP8_NOTFIRSTTIME_POOLED_SUPP,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP
0,100654,100200,1002,Alabama A & M University,Normal,AL,35762,Southern Association of Colleges and Schools C...,www.aamu.edu/,https://galileo.aamu.edu/NetPriceCalculator/np...,...,0.4048,0.2645,0.0137,0.315,0.3755,0.2958,0.0289,0.4224,0.2635,0.2852
1,100663,105200,1052,University of Alabama at Birmingham,Birmingham,AL,35294-0110,Southern Association of Colleges and Schools C...,www.uab.edu,uab.studentaidcalculator.com/survey.aspx,...,0.5448,0.12,0.0728,0.2583,0.5872,0.0817,0.1398,0.2618,0.3977,0.2008
2,100690,2503400,25034,Amridge University,Montgomery,AL,36117-3553,Southern Association of Colleges and Schools C...,www.amridgeuniversity.edu,www2.amridgeuniversity.edu:9091/,...,0.4647,0.1912,0.0148,0.3284,0.4391,0.2177,0.028,0.3645,0.4486,0.1589
3,100706,105500,1055,University of Alabama in Huntsville,Huntsville,AL,35899,Southern Association of Colleges and Schools C...,www.uah.edu,finaid.uah.edu/,...,0.5121,0.1593,0.0165,0.323,0.5361,0.1243,0.0245,0.3947,0.3476,0.2331
4,100724,100500,1005,Alabama State University,Montgomery,AL,36104-0271,Southern Association of Colleges and Schools C...,www.alasu.edu,www.alasu.edu/cost-aid/forms/calculator/index....,...,0.4226,0.0754,0.0254,0.5327,0.3133,0.1286,0.021,0.5804,0.1678,0.2308
5,100751,105100,1051,The University of Alabama,Tuscaloosa,AL,35487-0166,Southern Association of Colleges and Schools C...,www.ua.edu/,financialaid.ua.edu/net-price-calculator/,...,0.6376,0.1267,0.0073,0.2431,0.6817,0.0679,0.0142,0.2842,0.4599,0.2416
6,100760,100700,1007,Central Alabama Community College,Alexander City,AL,35010,Southern Association of Colleges and Schools C...,www.cacc.edu,https://www.cacc.edu/net-price-calculator/,...,0.2807,0.3502,0.0142,0.3794,0.2206,0.3858,0.0092,0.3258,0.2769,0.3881
7,100812,100800,1008,Athens State University,Athens,AL,35611,Southern Association of Colleges and Schools C...,www.athens.edu,https://24.athens.edu/apex/prod8/f?p=174:1:394...,...,0.5627,0.2276,0.0109,0.1797,0.649,0.1604,0.0181,0.2112,0.4741,0.2966
8,100830,831000,8310,Auburn University at Montgomery,Montgomery,AL,36117-3596,Southern Association of Colleges and Schools C...,www.aum.edu,www.aum.edu/current-students/financial-informa...,...,0.4884,0.2048,0.0134,0.4208,0.327,0.2388,0.0289,0.3737,0.2352,0.3622
9,100858,100900,1009,Auburn University,Auburn,AL,36849,Southern Association of Colleges and Schools C...,www.auburn.edu,https://www.auburn.edu/admissions/costcalc/fre...,...,0.7038,0.072,0.0062,0.2026,0.7405,0.0506,0.0143,0.3829,0.4571,0.1457
10,100937,101200,1012,Birmingham Southern College,Birmingham,AL,35254,Southern Association of Colleges and Schools C...,www.bsc.edu/,www.bsc.edu/fp/np-calculator.cfm,...,0.6196,0.0326,0.0031,0.3303,0.6319,0.0348,NaN,NaN,NaN,NaN
11,101028,1218200,12182,Chattahoochee Valley Community College,Phenix City,AL,36869,Southern Association of Colleges and Schools C...,www.cv.edu,www.cv.edu/about/consumer-information/,...,0.2463,0.1667,0.0155,0.5959,0.2216,0.167,0.0067,0.5705,0.1678,0.255
12,101073,1055400,10554,Concordia College Alabama,Selma,AL,36701,NaN,www.ccal.edu/,www.ccal.edu/admissions/net-pricing-calculator/,...,0.0957,0.505,0.006,0.2376,0.1037,0.6526,0,0.2075,0.0094,0.783
13,101116,1303906,13039,South University-Montgomery,Montgomery,AL,36116,Southern Association of Colleges and Schools C...,www.southuniversity.edu/montgomery#location=Mo...,www.southuniversity.edu/montgomery/net-price-c...,...,0.2574,0.6426,0,0.1263,0.2184,0.6553,0.0035,0.0804,0.2308,0.6853
14,101143,101500,1015,Enterprise State Community College,Enterprise,AL,36330-1300,Southern Association of Colleges and Schools C...,www.escc.edu,https://www.escc.edu/netprice/npcalc.htm,...,0.283,0.3396,0.0095,0.3663,0.3104,0.3138,0.004,0.4113,0.1707,0.414
15,101161,106000,1060,Coastal Alabama Community College,Bay Minette,AL,36507-2698,Southern Association of Colleges and Schools C...,www.coastalalabama.edu,www.coastalalabama.edu,...,0.297,0.0998,0.0119,0.5981,0.2845,0.1056,0.019,0.5704,0.2838,0.1268
16,101189,100300,1003,Faulkner University,Montgomery,AL,36109-3390,Southern Association of Colleges and Schools C...,www.faulkner.edu,www.faulkner.edu/net-price-calculator-form/,...,0.5333,0.1701,0.0057,0.3406,0.4638,0.19,0.0112,0.3825,0.3582,0.2481
17,101240,101700,1017,Gadsden State Community College,Gadsden,AL,35903,Southern Association of Colleges and Schools C...,www.gadsdenstate.edu,www.gadsdenstate.edu/net-price-calculator,...,0.2818,0.5138,0.0215,0.1641,0.2742,0.5402,0.0835,0.1191,0.2338,0.5636
18,101277,4187200,41872,New Beginning College of Cosmetology,Albertville,AL,35951,National Accrediting Commission of Career Arts...,www.nbccosmetology.com,nbccosmetology.com/sa/nbc_zonemap/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,101286,101800,1018,George C Wallace Community College-Dothan,Dothan,AL,36303-9234,Southern Association of Colleges and Schools C...,www.wallace.edu,www.wallace.edu/net_price_calculator.aspx,...,0.3583,0.294,0.0221,0.2986,0.2993,0.3799,0.043,0.2557,0.2743,0.427

In [9]:
# Look at the last 20 rows 
data.tail(20)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMAWDP8_NOTFIRSTTIME_POOLED_SUPP,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP
7092,47503311,4208611,42086,Relay Graduate School of Education - San Antonio,San Antonio,TX,782155155,Middle States Commission on Higher Education,relay.edu/location/relay-san-antonio,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7093,47503312,4208612,42086,Relay Graduate School of Education - Dallas-Fo...,Dallas,TX,752075155,Middle States Commission on Higher Education,relay.edu/location/relay-dallas-fort-worth,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7094,47503313,4208613,42086,Relay Graduate School of Education - Washingto...,Washington,DC,200375155,Middle States Commission on Higher Education,relay.edu/location/relay-washington-dc,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7095,47647001,4088301,40883,WestMed College - Merced,Merced,CA,953400000,NaN,www.westmedcollege.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7096,47662901,4189101,41891,Salon Institute - Columbus Campus,Lewis Center,OH,430359153,National Accrediting Commission of Career Arts...,www.saloninstitute.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7097,47691101,4205801,42058,SAE Institute of Technology San Francisco,Emeryville,CA,94608,NaN,usa.sae.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7098,48065701,869423,8694,Rasmussen College - Overland Park,Overland Park,KS,662102786,Higher Learning Commission,rasmussen.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7099,48079001,4218901,42189,Rocky Vista University - Southern Utah,Ivins,UT,847386756,Higher Learning Commission,www.rvu.edu/rvu-su/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7100,48092101,4220001,42200,Designer Barber & Stylist School -,Springdale,AR,727620990,National Accrediting Commission of Career Arts...,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7101,48133101,4213501,42135,Sharp Edgez Barber Institute - Buffalo,Buffalo,NY,142170000,Council on Occupational Education,www.sharpedgezbarberinstitute.com,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7102,48154401,4220901,42209,National Personal Training Institute of Cleveland,Highland Heights,OH,44143,Accrediting Council for Continuing Education &...,nptiohio.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7103,48305401,4224601,42246,Barber School of Pittsburgh - Ambridge,Ambridge,PA,150030000,NaN,www.bsp.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7104,48312401,108131,1081,Arizona State University at Tucson,Tucson,AZ,857454284,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7105,48312402,108161,1081,Arizona State University - ASU Colleges at Lak...,Lake Havasu City,AZ,864036877,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7106,48312403,108162,1081,Arizona State University at The Gila Valley,Thatcher,AZ,855525545,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7107,48312404,108163,1081,Arizona State University at Yuma,Yuma,AZ,853656900,Higher Learning Commission,www.asu.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7108,48387801,4223701,42237,Bay Area Medical Academy - San Jose Satellite ...,San Jose,CA,95113,Accrediting Council for Independent Colleges a...,www.bamasf.com/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7109,48400201,4228101,42281,High Desert Medical College,Lancaster,CA,935340000,Accrediting Council for Continuing Education &...,www.hdmc.edu,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7110,48778201,4221501,42215,BCI - Malden,Malden,MA,021480000,NaN,bostoncareer.org,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7111,49005401,4182601,41826,Health Career Institute- Lauderdale Lakes,Lauderdale Lakes,FL,333137268,Accrediting Commission of Career Schools and C...,www.hci.edu/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
# Look at a random sample of 20 rows    
data.sample(20)

,UNITID,OPEID,OPEID6,INSTNM,CITY,STABBR,ZIP,ACCREDAGENCY,INSTURL,NPCURL,...,OMAWDP8_NOTFIRSTTIME_POOLED_SUPP,OMENRUP_NOTFIRSTTIME_POOLED_SUPP,OMENRYP_FULLTIME_POOLED_SUPP,OMENRAP_FULLTIME_POOLED_SUPP,OMAWDP8_FULLTIME_POOLED_SUPP,OMENRUP_FULLTIME_POOLED_SUPP,OMENRYP_PARTTIME_POOLED_SUPP,OMENRAP_PARTTIME_POOLED_SUPP,OMAWDP8_PARTTIME_POOLED_SUPP,OMENRUP_PARTTIME_POOLED_SUPP
6762,15098703,991713,9917,Ivy Tech Community College-East Central,Muncie,IN,473029448,Higher Learning Commission,www.ivytech.edu/muncie/,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5259,449117,499201,4992,Platt College-Miller-Motte-Cary,Cary,NC,27518-7171,NaN,www.miller-motte.edu,disclosure.miller-motte.edu/npc/npcalc-cary.htm,...,0.5799,0.3984,0,0.0244,0.5854,0.3902,0,0.024,0.503,0.4729
2033,182564,1036300,10363,Western Nevada College,Carson City,NV,89703-7399,Northwest Commission on Colleges and Universities,www.wnc.edu,www.wnc.edu/NetPriceCalculator/npcalc.htm,...,0.1662,0.4176,0.019,0.302,0.2858,0.3932,0.0211,0.2911,0.1164,0.5713
1185,153621,187100,1871,Iowa Wesleyan University,Mount Pleasant,IA,52641,Higher Learning Commission,https://www.iw.edu,https://www.iw.edu/scholarship-calculator/,...,0.5964,0.1857,0,0.3974,0.4275,0.1751,0,0.1154,0.4423,0.4423
649,131496,144500,1445,Georgetown University,Washington,DC,20057-0001,Middle States Commission on Higher Education,www.georgetown.edu,finaid.georgetown.edu/consumer-info#Net%20Price,...,0.8914,0.0471,0.0003,0.0409,0.9478,0.011,0.0286,0.2143,0.5286,0.2286
254,111799,2332813,23328,CET-Salinas,Salinas,CA,93906,Council on Occupational Education,https://cetweb.edu,https://cetweb.edu/tuition,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1860,176479,244700,2447,William Carey University,Hattiesburg,MS,39401-5499,Southern Association of Colleges and Schools C...,www.wmcarey.edu,https://wmcarey.studentaidcalculator.com/surve...,...,0.6361,0.2247,0.0065,0.1106,0.6521,0.2308,0.0053,0.2487,0.4233,0.3228
3454,225432,361200,3612,University of Houston-Downtown,Houston,TX,77002-1014,Southern Association of Colleges and Schools C...,www.uhd.edu,www.uhd.edu/financial/cost/Pages/financial-cos...,...,0.5188,0.1887,0.0323,0.348,0.4335,0.1862,0.0278,0.3325,0.4034,0.2363
747,136765,2511700,25117,Ridge Technical College,Winter Haven,FL,33881-9518,Council on Occupational Education,www.ridge.edu/,www.ridge.edu/,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1557,166027,215500,2155,Harvard University,Cambridge,MA,02138,New England Commission on Higher Education,www.harvard.edu,college.harvard.edu/financial-aid/net-price-ca...,...,0.75,0.1324,0.0036,0.0051,0.9812,0.0101,0,0.1429,0.6667,0.1905
4517,417406,3090600,30906,Cobb Beauty College Inc,Kennesaw,GA,30144-2828,NaN,www.cobbbeautycollege.edu,www.cobbbeautycollege.edu/NetPrice/npcalc.htm,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1883,177278,246200,2462,Eden Theological Seminary,Webster Groves,MO,63119-3192,Higher Learning Commission,www.eden.edu,www.eden.edu,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4914,441238,3592400,35924,Irell & Manella Graduate School of Biological ...,Duarte,CA,91010-3000,Western Association of Schools and Colleges Se...,https://www.cityofhope.org/grad-school,https://www.cityofhope.org/grad-school,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5687,458885,145984,1459,Strayer University-Arkansas,Little Rock,AR,72211,Middle States Commission on Higher Education,www.strayer.edu/arkansas/little-rock,https://strayer.aidcalc.com/netprice.htm,...,0.1215,0.547,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,PrivacySuppressed,0.0141,0.3239,0.108,0.554
5311,450021,3294301,32943,Blue Cliff College-Houma,Houma,LA,70360,Accrediting Commission of Career Schools and C...,bluecliffcollege.edu/,bluecliffcollege.edu/cosmo-npcalc/cosmetologyn...,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5232,448576,2179948,21799,Argosy University-The Art Institute of Califor...,San Bernardino,CA,92408-2800,NaN,www.artinstitutes.edu/inlandempire,www.artinstitutes.edu/inland-empire/tuition-ai...,...,0.4469,0.5307,0,0.0209,0.3837,0.5954,0,0.0156,0.3074,0.677
6584,489937,295600,2956,Piedmont International University,Winston-Salem,NC,27101,Transnational Association of Christian College...,www.piedmontu.edu,webtools.piedmontu.edu/NetPrice/npcalc.htm,...,0.3205,0.6731,0,0.0085,0.2851,0.7064,0.0104,0,0.1771,0.8125
6036,476869,4203500,42035,Austin Kade Academy,Idaho Falls,ID,83404-5540,National Accrediting Commission of Career Arts...,www.austinkade.com,www.austinkade.com,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2985,212054,325600,3256,Drexel University,Philadelphia,PA,19104,Middle States Commission on Higher Education,www.drexel.edu,drexel.edu/drexelcentral/finaid/prospective-st...,...,0.575,0.2356,0.0009,0.2127,0.7036,0.0827,0.0076,0.2469,0.3491,0.3964
687,133881,146900,1469,Florida Institute of Technology,Melbourne,FL,32901-6975,Southern Association of Colleges and Schools C...,www.fit.edu,https://fit.studentaidcalculator.com/survey.aspx,...,0.6378,0.2229,0.002,0.0985,0.5911,0.3084,0,0.0233,0.3488,0.6279

Read (with naked eyes, not computer) the dictionary and find out the definitions of the following 12 columns and copy the text next to the column name
- UNITID: Unit ID for institution           
- INSTNM:  Institution name        
- CITY: City in which University is located 
- STABBR: State Abbrevation
- ZIP: Zip Code of the location of the University             
- ADM_RATE: Admission Rate in a particular college 
- UGDS: Undergrads Count  
- TUITIONFEE_IN: In Tuition Fee for a particular college  
- MN_EARN_WNE_P10: Mean earnings of students working and not enrolled 10 years after entry

In [11]:
# reimport the data with above 12 columns (ignore all other variables)
data=pd.read_csv('CollegeScorecard_Raw_Data/MERGED2017_18_PP.csv', usecols = ['UNITID','INSTNM','CITY','STABBR','ZIP',
                                                                              'ADM_RATE','UGDS','TUITIONFEE_IN','MN_EARN_WNE_P10'])
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7112 entries, 0 to 7111
Data columns (total 9 columns):
UNITID             7112 non-null int64
INSTNM             7112 non-null object
CITY               7112 non-null object
STABBR             7112 non-null object
ZIP                7112 non-null object
ADM_RATE           2037 non-null float64
UGDS               6364 non-null float64
TUITIONFEE_IN      4021 non-null float64
MN_EARN_WNE_P10    0 non-null float64
dtypes: float64(4), int64(1), object(4)
memory usage: 500.2+ KB

In [12]:
data.head(5)

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
0,100654,Alabama A & M University,Normal,AL,35762,0.9027,4824.0,9857.0,NaN
1,100663,University of Alabama at Birmingham,Birmingham,AL,35294-0110,0.9181,12866.0,8328.0,NaN
2,100690,Amridge University,Montgomery,AL,36117-3553,NaN,322.0,6900.0,NaN
3,100706,University of Alabama in Huntsville,Huntsville,AL,35899,0.8123,6917.0,10280.0,NaN
4,100724,Alabama State University,Montgomery,AL,36104-0271,0.9787,4189.0,11068.0,NaN

In [18]:
# Find out the 10 colleges that are hardest to get in (top 10)
## This can be found using the admission rate. The lowest admission rate of any
## college suggests that it is tougher to get in.
toughest_colleges=data.nsmallest(10, ['ADM_RATE']) 
toughest_colleges.head(10)

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
2974,211635,Citizens School of Nursing,New Kensington,PA,15068-6525,0.0000,158.0,NaN,NaN
5226,448309,Shorter University-College of Adult & Professi...,Rome,GA,30165,0.0000,113.0,9680.0,NaN
6112,480912,Gemini School of Visual Arts & Communication,Cedar Park,TX,78613,0.0000,18.0,NaN,NaN
6664,491288,University of Wisconsin-Milwaukee Flex,Milwaukee,WI,53201,0.0000,501.0,6750.0,NaN
2978,211893,Curtis Institute of Music,Philadelphia,PA,19103,0.0330,131.0,2675.0,NaN
3979,243744,Stanford University,Stanford,CA,94305,0.0473,7056.0,49617.0,NaN
1557,166027,Harvard University,Cambridge,MA,02138,0.0516,7532.0,48949.0,NaN
2302,192110,The Juilliard School,New York,NY,10023-6588,0.0592,486.0,43170.0,NaN
2123,186131,Princeton University,Princeton,NJ,08544-0070,0.0641,5246.0,47140.0,NaN
2233,190150,Columbia University in the City of New York,New York,NY,10027,0.0661,8170.0,57208.0,NaN

In [20]:
# Below are the names of the colleges
toughest_colleges['INSTNM']

2974                           Citizens School of Nursing
5226    Shorter University-College of Adult & Professi...
6112         Gemini School of Visual Arts & Communication
6664               University of Wisconsin-Milwaukee Flex
2978                            Curtis Institute of Music
3979                                  Stanford University
1557                                   Harvard University
2302                                 The Juilliard School
2123                                 Princeton University
2233          Columbia University in the City of New York
Name: INSTNM, dtype: object

In [26]:
# 10. Find out the average in-state tuition of top 10
#toughest_colleges.mean()
toughest_colleges.loc[:,'TUITIONFEE_IN'].mean()

33148.625

In [27]:
# Find out the average earnings of graduates from the top 10
# If we look at the data, all the entires have a null vale (missing data)
print('Average earnings of graduates from the top 10: ')
toughest_colleges.loc[:,'MN_EARN_WNE_P10'].mean()

nan

In [28]:
# Find out the 10 colleges that are easiest to get in (bottom 10)
# Easiest colleges mean that the admission rate has to be higher

easiest_colleges=data.nlargest(10, ['ADM_RATE']) 
easiest_colleges.head(10)

,UNITID,INSTNM,CITY,STABBR,ZIP,ADM_RATE,UGDS,TUITIONFEE_IN,MN_EARN_WNE_P10
24,101453,Heritage Christian University,Florence,AL,35630-9977,1.0,59.0,11232.0,NaN
240,110918,California Christian College,Fresno,CA,93727,1.0,16.0,9330.0,NaN
370,118161,Lytles Redwood Empire Beauty College Inc,Santa Rosa,CA,95403,1.0,158.0,NaN,NaN
472,123280,Shasta Bible College and Graduate School,Redding,CA,96002,1.0,42.0,12060.0,NaN
559,127653,Naropa University,Boulder,CO,80302-6697,1.0,384.0,31790.0,NaN
571,127954,Montessori Education Center of the Rockies,Boulder,CO,80301,1.0,16.0,NaN,NaN
652,131830,National Conservatory of Dramatic Arts,Washington,DC,20007,1.0,32.0,9900.0,NaN
665,132842,Carlos Albizu University-Miami,Miami,FL,33172-2209,1.0,236.0,12444.0,NaN
887,142090,Boise Bible College,Boise,ID,83714-1220,1.0,128.0,12080.0,NaN
1011,147165,Midstate College,Peoria,IL,61614-3595,1.0,274.0,16230.0,NaN

In [31]:
# Find out the average in-state tuition of the bottom 10
print('Average in-state tuition fee of the bottom 10: ')
easiest_colleges.loc[:,'TUITIONFEE_IN'].mean()

Average in-state tuition fee of the bottom 10

14383.25

In [32]:
# Find out the average earnings of graduates from the bottom 10
# If we look at the data, all the entires have a null vale (missing data)
print('Average earnings of graduates from the bottom 10: ')
easiest_colleges.loc[:,'MN_EARN_WNE_P10'].mean()

Average earnings of graduates from the bottom 10:

nan